services:
  - type: web
    name: pokechat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: COLLECTION_POKEMON
        sync: false